---
functional:
  - Пользователь должен иметь возможность зарегестрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность создавать игру
  - Пользователь должен иметь возможность настраивать параметры игры при создании
  - Пользователь должен иметь возможность присоединиться к созданной другим пользователем игре
  - Пользователь должен иметь возможность выбирать язык програмирования
  - Пользователь должен иметь возможность выбирать задачи на языках русском и английском
  - Пользователь должен иметь возможность общаться в чате
  - Другие пользователи могут следить за ходом игр
  - Пользователь должен иметь возможность сдаться
  - Пользователи получают очки за игры, на основе которых строится рейтинг за неделю, месяц и за все время
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (опера, сафари, фаерфокс)
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь имеет возможность подключиться к игре до ее завершения
  - Сайт с возможность обратной связи
  - Пользователь имеет возможность настроить свой профиль(Your name, Your weapon, Your clan, Select sound type (Dendy CSS tandard Silent), Select sound level) 
  - Эксплуатация сайта должна соответствовать требованиям законодательства РФ
